language: erlang
python:
- 2.7
otp_release:
- 18.0
- 18.1
sudo: true
before_install:
- sudo apt-get -y update
- sudo apt-get -y install libicu-dev libmozjs185-dev pkg-config help2man libcurl4-openssl-dev
- sudo apt-get -y install libtool automake autoconf autoconf-archive
- sudo apt-get -y install python-setuptools
install:
- "./support/bootstrap_travis.sh"
before_script:
- make spec
- "/home/travis/build/barrel-db/barrel-platform/_build/default/rel/barrel/bin/barrel start"
- sudo easy_install -f http://funkload.nuxeo.org/snapshots/ -U funkload
- git clone https://github.com/barrel-db/specs.git /home/travis/swagger
- sudo pip install -r /home/travis/swagger/requirements.txt
script:
- ./rebar3 eunit --dir="test"
- ./rebar3 ct
- cd /home/travis/swagger && python -m test.test_swagger
notifications:
  email:
  - bchesneau@gmail.com
  slack:
    secure: v07PkcR4WofdFjGzkAeG0wPNPV798C/Jj81hoIZ2BHiV2WDomksvIQORY4J0W6qqgHoEYeQ35AkjrrheuQzVtmKc+BgW7xyrS4v4xLuP6c1A5uC+KYzUOCHXjPmyi7lH4H25e/HmCTK0EHhtyH5FSOfglEIgBkOUCAwQ1EbppNVefJ6zNMegjwwKUf2JgNMYfeeX2xAHCKCEbULYa/Lxc1+87pFwMc9lbO8LQYMKuyZob+7h1a0epeti3aElMd20wEFx69E4y5/Af7BkB973FEYaMkSr/iSYOkKd+0HcR6nakAYjxd6zdXbKy5UgHS7rC3iB5y3N5UHyowPVt+i5q8JWHtOgPKL8dEvtcXrA0ICk1JZb/aW+3kWg9f+nn2osXGZC27XQO7nzPfkDyFgOt+gq1nQ7K8KrPuGrntEILib9ZQQ9pmuzxE+LbtGfrcoU+jJph2fEWxO4cENC9W3DAaVV9ZpmIm4Gs4WGJae8KYXUnrWXvDzBvubX+ofYSWkFhtPjulW94MizdELEOu4kLl1QUXlFpDDcNRO5sa3IEpRvCkeVyaJjyL4GYTfw1gV0NmsROz7IZmOqMf6CG66hc5JJgvj61Km5P/Se6sWN2bZE6uUG6UgizIsYjCp8kT0Gqlc2sJHHjZDJg5iTAf5NmUVdMqBYr167WTKlCjt2sf8=
