-compile({pulse_replace_module, [{application, pulse_application}]}).
-compile({pulse_replace_module, [{application_controller, pulse_application_controller}]}).
-compile({pulse_replace_module, [{application_master, pulse_application_master}]}).
-compile({pulse_replace_module, [{application_starter, pulse_application_starter}]}).
-compile({pulse_replace_module, [{gen, pulse_gen}]}).
-compile({pulse_replace_module, [{gen_event, pulse_gen_event}]}).
-compile({pulse_replace_module, [{gen_fsm, pulse_gen_fsm}]}).
-compile({pulse_replace_module, [{gen_statem, pulse_gen_statem}]}).
-compile({pulse_replace_module, [{gen_server, pulse_gen_server}]}).
-compile({pulse_replace_module, [{proc_lib, pulse_proc_lib}]}).
-compile({pulse_replace_module, [{supervisor, pulse_supervisor}]}).
-compile({pulse_replace_module, [{sys, pulse_sys}]}).

